//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo3.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.Partner_product = new HashSet<Partner_product>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_type { get; set; }
        public string name { get; set; }
        public string name_direktor { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string adress_partner { get; set; }
        public string inn { get; set; }
        public Nullable<int> rang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner_product> Partner_product { get; set; }
        public virtual Partners_type Partners_type { get; set; }
    }
}
