//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo3.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_product
    {
        public int id { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_partnera { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Product Product { get; set; }
    }
}
